### PR TITLE
Simplify example.html

### PR DESCRIPTION
**Pull request by feross**
- Remove async -- not needed (use setTimeout)
- Remove debug -- not needed (use console.log)
- Remove libs.js -- not needed anymroe
- Move JS into example.html in root folder

- Remove http-server, since this simpler example file can now be opened
directly in the browser (with a file:/// url)
- Remove unneeded npm run commands

- Add minified, built JS file to repo (used by the example file)
- Alphabetize keywords in `package.json`
- Convert tabs to spaces

I think this approach is a lot simpler and we don't lose any functionality of the `example.html` file. Let me know what you think @roccomuso 👍 

As an added bonus, we now commit the `min.js` file in the repo, which is useful to users who don't use browserify.

### CODE REVIEW

**Comment by roccomuso** [comment]
:+1: Cool! I Guess we could bump the version and publish it on npm.

**Review by roccomuso — APPROVED** [review]
Great ;) Approved

**Comment by feross** [comment]
Released as 1.1.0

**Comment by feross** [comment]
Thanks for the review! 👍

**Pull request merged**
